#ifndef APP_CONFIG
#define APP_CONFIG

#define POSTPROCESS_TYPE    POSTPROCESS_FD_BLAZEFACE_UI

#define AI_FD_BLAZEFACE_PP_NB_KEYPOINTS      (6)
#define AI_FD_BLAZEFACE_PP_NB_CLASSES        (1)
#define AI_FD_BLAZEFACE_PP_IMG_SIZE          (128)
#define AI_FD_BLAZEFACE_PP_OUT_0_NB_BOXES    (512)
#define AI_FD_BLAZEFACE_PP_OUT_1_NB_BOXES    (384)
#define AI_FD_BLAZEFACE_PP_MAX_BOXES_LIMIT   (3)
#define AI_FD_BLAZEFACE_PP_CONF_THRESHOLD    (0.8f)
#define AI_FD_BLAZEFACE_PP_IOU_THRESHOLD     (0.5f)

#endif
